### PR TITLE
New Feature: support for reads compressed in gzip and bzip2 format

### PR DESCRIPTION
**Pull request by crashfrog**
This PR adds support for reads compressed in gzip and bzip2 format; compression formats are auto-detected and compressed reads are decompressed to a temporary file for subsequent processing by the ECTyper pipeline.

Galaxy tool definition XML file is also updated to support the broader ecosystem of Galaxy FASTQ types (no longer requiring space-expensive implicit conversion for many pipelines.)

### CODE REVIEW

**Comment by kbessonov1984** [comment]
Thank you for your contribution. On a quick glance, all looks good and the support for compressed files would really be useful for the raw reads inputs in FASTQ format.  Also thank you for fixing the galaxy wrapper files, I will use those changes and include them in the ToolShed release so that compressed files are also better supported by the Galaxy Project instance.
I will do more checks in my VMs and Galaxy instances and then report here and merge. This PR probably will be included as part of the next release (version 1.0.5)

**Comment by crashfrog** [comment]
Any word from the testing or a timeframe for release?

**Comment by crashfrog** [comment]
Hi, just checking in again, wondering how the testing is going

**Comment by kbessonov1984** [comment]
Hi, I was on vacation the past week. I am now doing testing and we should be done soon.  Do you need just source code merge or new conda and Galaxy release? I was just thinking of doing new feature merge and new release later. Let me know your plans and new feature release purpose. As alternative we can do 1.0.1 release.

**Comment by kbessonov1984** [comment]
I am getting gzip input file name error for the compressed reads that need to be fixed. The genome name regex needs to be fixed.

Command: `ectyper -i SRR12852136_1.fastq.gz -o test --verify`

In addition, I am thinking to add ability to combine both forward and reverse reads, but that feature could wait. Most use cases use assemblies anyway.

```
2022-07-20 22:42:07,510 ectyper      INFO     BLAST output file against reference alleles is written at test/blast_output_alleles.txt
Traceback (most recent call last):
  File "/usr/local/bin/ectyper", line 4, in <module>
    __import__('pkg_resources').run_script('ectyper==1.0.0', 'ectyper')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.9/dist-packages/ectyper-1.0.0-py3.9.egg/EGG-INFO/scripts/ectyper", line 13, in <module>
    ectyper.run_program()
  File "/usr/local/lib/python3.9/dist-packages/ectyper-1.0.0-py3.9.egg/ectyper/ectyper.py", line 161, in run_program
    final_predictions = predictionFunctions.add_non_predicted(
  File "/usr/local/lib/python3.9/dist-packages/ectyper-1.0.0-py3.9.egg/ectyper/predictionFunctions.py", line 581, in add_non_predicted
    'species': ecoli_dict[gname]["species"]
KeyError: 'SRR12852136_1.fastq'
```

**Comment by crashfrog** [comment]
Alright, never mind - trying to debug this has simply resulted in _more_ bugs and the inability to complete any planemo tests, and I'm just not familiar enough with the codebase to figure out what's wrong. Plus I no longer need ECTyper to have native support for compressed reads anyway.

**Comment by kbessonov1984** [comment]
No worries, I will fix it shortly. It is a nice feature to have and would be bad to miss it.

**Comment by kbessonov1984** [comment]
This feature will be implemented in the version 2.0.0 of the tool and is now available at `v2.0.0` branch at [https://github.com/phac-nml/ecoli_serotyping/tree/v2.0.0](https://github.com/phac-nml/ecoli_serotyping/tree/v2.0.0). Now both gunzip compressed FASTA and FASTQ inputs are supported

**Pull request closed without merging**
